### ISSUE TITLE
Create AppEnv and AppMint models to connect Apps to Clusters and Mints

### ISSUE THREAD

**Issue by beeman** [kin-labs/mogami#181]
Follow-up of #173 

We want to have an `AppEnv` model that connects the app to a cluster and a mint.

One `App` has one or more `AppEnv`. 

Each `AppEnv` connects to one `Cluster`
Each `AppEnv` connects to one `AppMint` which connects to one `Mint`

The `AppMint` model is an intermediary model that holds extra data. For instance, which wallet pays the fees for this mint, and if the 'memo' field needs to be added in transactions. 

```
App => AppEnv (devnet)  => Cluster (solana-devnet)
                        => AppMint
                              - KinDesK3...
       AppEnv (mainnet) => Cluster (solana-mainnet)
                        => AppMint
                              - kinXdEcp...
```

- [x] Add `AppEnv` and `AppMint` models #224 
- [x] Add 'Enviromnets' to the Admin section. #228 
- [x] Add an `environment` property to the SDKs #230
- [x] Pass along `environment` in any related SDK operations #230
- [x] Adjust AppConfig to show multiple mints
- [x] Move from single airdrop to Mint #232 
- [x] Switch AppWebhooks to AppEnv #233 
- [x] Switch AppTransactions to AppEnv #235 
- [x] Remove model `wallets` from app #236
- [x] Remove last usage of `solana` instance on ApiCoreDataAccessService #237

**Comment by beeman** [comment]
This has been implemented, everything is now scoped to the `AppEnv`, `AppMint` or `Cluster`.
